name: Test Build Publish

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Get Package Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main

    - name: Test and Build Angular Application
      run: |
        npm ci
        npm run test:prod
        npm run build:prod

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: morriswa
        password: ${{ secrets.DOCKERPASSWORD }}

    - name: Docker Build and Publish
      run: |
        docker build . -t morriswa/salon-ng:${{ steps.package-version.outputs.current-version }}
        docker push morriswa/salon-ng:${{ steps.package-version.outputs.current-version }}
