name: Build and Publish with Docker

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Package Version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main

    - name: Test Angular Application
      run: |
        npm i
        npm run test:prod

    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        username: morriswa
        password: ${{ secrets.DOCKERPASSWORD }}

    - name: Docker Build and Publish
      run: |
        docker build . -t morriswa/salon-ng:${{ steps.package-version.outputs.current-version }}
        docker push morriswa/salon-ng:${{ steps.package-version.outputs.current-version }}
